#!/usr/bin/env lua --FOR-LINTING-AND-FORMATTING-DON'T-RUN
-- This file is *not* meant to be ran or required. It's only lua for syntax highlighting.
error("You can't require the todo file!")
-- TODO: implement notification center (only in awesome-git)
-- awesome-shell@widgets/noti-center.lua is a good place to start
-- This is not possible in v4.3 because naughty is too simple and doesn't provide signals

--TODO: WIDGETS
--Rewrite awful.wiget.layoutbox to use material.icon (for proper svg scaling)
---   See: widget.layout-box
--Use exponential scale. Check ./widget/backlight-adjust.lua for an example
