#!/usr/bin/env lua --FOR-LINTING-AND-FORMATTING-DON'T-RUN
-- This file is *not* meant to be ran or required. It's only lua for syntax highlighting.
if true then return end

--TODO: Find better way to abstract in rc.lua when require is effectively offlimits (due to NS installation)
--TODO: CLEANUP
--Remove unused code
--  Keep the widgets for the sake of convenience

--TODO: WIDGETS
--Improve all widgets that came with TitusTech's clone.
--  Return functions, take args, default programs, etc...
--  These don't work (I think)
--    Tempurature - WORKS? test.
--    Volumne - works? patterns?
--    WiFi - spawns defined program, needs fixed. Defined interface. relies on iw - not stable
--    Bluetooth - Not even exists.
--    Hard-Drive - Relies on `df`, and only checks /home
--    Package updater - relies on pamac - not even debian supported.
--    RAM - Uses glob, by accident. External process, can be simplified?
--Make the package widget work with apt (dpkg?) (or any given package).
--  Accept an argument for commands/hooks
--    apt-get -q -y --ignore-hold --allow-change-held-packages --allow-unauthenticated ---simulate dist-upgrade | /bin/grep  ^Inst | wc -l --> 'updates'
--    /usr/lib/update-notifier/apt-check 2>&1 --> 'security_updates;regular_updates'
--Use exponential scale. Check ./widget/backlight-adjust.lua for an example
