---@class GCancellableStatic
---@field new fun(): GCancellable

---@class GCancellable
---@field cancel fun(self: GCancellable)
---callback is called at most once, either directly at the time of the connect if cancellable is already cancelled, or when cancellable is cancelled in some thread.
---@field connect fun(self: GCancellable, callback: fun()): handler_id: number|0
---@field disconnect fun(self: GCancellable, handler_id: number)
---@field is_cancelled fun(self: GCancellable): boolean
---Resets cancellable to its uncancelled state.
---Note: BAD IDEA™. Just create a new cancellable
---@field reset fun(self: GCancellable)
