---@alias GOutputStreamSpliceFlags "NONE" No flags set.
---|"CLOSE_SOURCE" Close the source stream after splicing.
---|"CLOSE_TARGET" Close the target stream after splicing.

---@class GOutputStream -- An abstract class for writing data to a stream.
---Same as write_async() but takes a GBytes input instead
---@field write_bytes_async fun(self: GOutputStream, content: GBytes, io_priority: integer, cancellable?: GCancellable, callback?: GAsyncReadyCallback<GOutputStream>)
---@field write_bytes_finish fun(self: GOutputStream, task: userdata): written: integer?, GError?
---@field write_bytes fun(self: GOutputStream, buffer: GBytes, cancellable?: GCancellable): written: integer, GError?
---WARNING: This function *does not* copy the contents of `contents` and so it must not be freed. Use write_bytes_async() instead.
---@field write_async fun(self: GOutputStream, content: string, len: integer, io_priority: integer, cancellable?: GCancellable, callback?: GAsyncReadyCallback<GOutputStream>)
---@field write_finish fun(self: GOutputStream, task: userdata): written: integer?, GError?
---@field write fun(self: GOutputStream, buffer: string, count: integer, cancellable?: GCancellable): written: integer, GError?
---@field close fun(self: GOutputStream): boolean, GError?
---@field close_async fun(self: GOutputStream, io_priority: integer, cancellable?: GCancellable, callback?: GAsyncReadyCallback<GOutputStream>)
---@field close_finish fun(self: GOutputStream, task: userdata): boolean?, GError?
---@field splice fun(self: GOutputStream, source: GInputStream, flags: Flags<GOutputStreamSpliceFlags>, cancellable?: GCancellable): size: integer, GError?
---@field splice_async fun(self: GOutputStream, source: GInputStream, flags: Flags<GOutputStreamSpliceFlags>, io_priority: integer, cancellable?: GCancellable, callback?: GAsyncReadyCallback<GOutputStream>)
---@field splice_finish fun(self: GOutputStream, task: userdata): size: integer?, GError?
