local require = require("util.rel_require")

local beautiful = require("beautiful")
local config_file_dir = require(..., "conffile_dir") ---@module "configuration.apps.conffile_dir"
local strings = require("util.strings")
local write_async = require("util.file.write_async")

local function rofi_conf(prop, val)
  if not prop or not val then return nil end
  -- Add new property
  return ("%s: %s;"):format(prop, val)
end
local conf = strings.line2str({
  "// This file is automatically generated. Do not edit",
  "* {",
  rofi_conf("background-color", beautiful.rofi_background_color),
  rofi_conf("text-color", beautiful.rofi_text_color),
  rofi_conf("selbg", beautiful.rofi_selbg),
  rofi_conf("actbg", beautiful.rofi_actbg),
  rofi_conf("urgbg", beautiful.rofi_urgbg),
  rofi_conf("entry-background", beautiful.rofi_entry_background),
  rofi_conf("winbg", beautiful.rofi_wingb),
  "}",
  "//vim:ft=css:",
})

write_async(config_file_dir .. "/rofi/dynamic.rasi", conf) -- this file should be ignored

---create a rofi command
---@param ... string
---@return string[]
local function rofi_command(...)
  -- Thanks to jo148 on github for making rofi dpi aware!
  local xres = require("beautiful").xresources
  local args = { ... }
  -- Ends in -show to pick default, but can be overridden by appending a mode
  local cmd = {
    "rofi",
    "-dpi",
    tostring(xres.get_dpi()),
    "-width",
    tostring(xres.apply_dpi(400)),
    "-theme",
    config_file_dir .. "/rofi/config.rasi",
    "-show",
  }
  for i, v in ipairs(args) do
    if type(v) ~= "string" then error(string.format("Invalid argument #%d. Expected string, got %s", i, type(v)), 2) end
    table.insert(cmd, v)
  end
  return cmd
end
return rofi_command
