local require = require("util.rel_require")

local beautiful = require("beautiful")
local config_file_dir = require(..., "apps.conffile_dir") ---@module "configuration.apps.conffile_dir"
local strings = require("util.strings")
local write_async = require("util.file.write_async")

---@param p string?
---@param v string?
---@param quote boolean?
---@return string?
local function prop(p, v, quote)
  if not p or not v then return nil end
  local format = quote and '%s: "%s"' or "%s: %s"
  -- Add new property
  return ("\t" .. format .. ";"):format(p, v)
end

local conf = strings.line2str({
  "// This file is automatically generated. Do not edit",
  "* {",
  prop("--bg", beautiful.rofi_bg),
  prop("--fg", beautiful.rofi_fg),
  prop("--active-background", beautiful.rofi_active_background),
  prop("--font", beautiful.font, true),
  "}",
  "// vim" .. ":ft=css commentstring=//%s:", -- hack to stop vim from processing this modeline here
})

write_async(config_file_dir .. "/rofi/dynamic.rasi", conf) -- this file should be ignored
