name: Generate README
on:
  push:
  pull_request:
    paths:
      - "README.md" # This isn't needed, but it's a good sanity check
      - "README.tmpl.md"
      - "setup.lua"
  workflow_dispatch:
jobs:
  generate-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      # - uses: leafo/gh-actions-lua@v10
      #   with:
      #     luaVersion: "5.3" # Ubuntu lua-lgi supports 5.1-5.3
      - name: Install lgi/dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          # We don't strictly need awesome, but it includes all the dependencies I expect to have
          # NOTE: If lua5.3 is changed, the below ln must be changed to match
          packages: awesome lua5.3
          version: 1.0
      - run: sudo ln -sf /usr/bin/lua5.3 /usr/bin/lua
      - name: Generate README
        run: ./scripts/gen-readme
      - name: CLOC
        uses: djdefi/cloc-action@6
        with:
          options: --md --report-file=cloc.md --hide-rate
        # Note: initial newline is required because files don't end with one
      - run: |
          printf '\n%s\n' '### Lines of code' >> README.md
          cat cloc.md >> README.md
          rm cloc.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Generate README"
          file_pattern: README.md
