name: Generate Documentation
on:
  push:
  pull_request: { paths: ["README.md", "README.tmpl.md", "setup.lua"] }
  workflow_dispatch:
jobs:
  generate-package-list:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@master
      - name: Install lgi/dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          # We don't strictly need awesome, but it includes all the dependencies I expect to have
          # NOTE: If lua5.3 is changed, the below ln must be changed to match
          packages: awesome lua5.3
          version: 1.0
      - run: sudo ln -sf /usr/bin/lua5.3 /usr/bin/lua
      - name: Generate packages.md
        run: ./scripts/gen-package-list >| docs/packages.md
      - name: Commit packages.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Generate packages.md"
          file_pattern: docs/packages.md

  generate-cloc:
    permissions: { contents: write }
    uses: aarondill/github-actions/.github/workflows/gen-readme.yml@main
    with:
      template-file: docs/README.tmpl.md
